trigger: none

parameters:
  - name: repository
    displayName: 'Azure DevOps Repository Name or ID'
    type: string
    default: ''

jobs:
- job: CheckMainBranch
  displayName: 'Check Main Branch'
  pool:
    vmImage: 'ubuntu-latest'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'))
  steps:
    - checkout: none
    - script: |
        echo "Checking repository: ${{ parameters.repository }}"
        
        # Get repo details from the REST API
        response=$(curl -sS \
          -H "Authorization: Bearer $SYSTEM_ACCESSTOKEN" \
          -H "Content-Type: application/json" \
          "$ORGANIZAION_URL$PROJECT_NAME/_apis/git/repositories/${{ parameters.repository }}?api-version=7.1-preview.1")

        echo "API Response: $response | jq ."

env:
  SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  ORGANIZAION_URL: $(System.CollectionUri)
  PROJECT_NAME: $(System.TeamProject)