trigger: none

parameters:
  - name: repository
    displayName: 'Azure DevOps Repository Name or ID'
    type: string
    default: ''

jobs:
- job: CheckMainBranch
  displayName: 'Check Main Branch'
  pool:
    vmImage: 'ubuntu-latest'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'))
  steps:
    - checkout: none
    - bash: |
        set -euo pipefail
        
        echo "Checking repository: ${{ parameters.repository }}"
        
        API_URL = "$ORGANIZAION_URL$PROJECT_NAME/_apis/git/repositories/${{ parameters.repository }}?api-version=7.1-preview.1"
        echo "API URL: $API_URL"

        # Get repo details from the REST API
        http_status=$(curl -sS -o response.json -w "%{http_code}" \
          -H "Authorization: Bearer $SYSTEM_ACCESSTOKEN" \
          -H "Content-Type: application/json" \
          "$API_URL" || echo "000")

        echo "HTTP Status: $http_status"
        echo "API Response: $response"

env:
  SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  ORGANIZAION_URL: $(System.CollectionUri)
  PROJECT_NAME: $(System.TeamProject)