trigger: none

pool:
  name: 'PeymanLaptopAgent

parameters:
  - name: repository
    displayName: 'Azure DevOps Repository Name or ID'
    type: string
    default: ''

jobs:
- template: templates/manage-default-branch.yml
  parameters:
    repository: ${{ parameters.repository }}
    